const ADD_PRODUCT = "SHOPPING_CAR ADD_PRODUCT";
const REMOVE_PRODUCT = "SHOPPING_CAR REMOVE_PRODUCT";
const SET_FORM_STEP = "SET_FORM_STEP";
const RESET_STATE = "RESET_STATE";
const DISABLE_STEP = "DISABLE_STEP";
const ADD_PRODUCT_QUANTITY = "ADD_PRODUCT_QUANTITY";
const DISCOUNT_PRODUCT_QUANTITY = "DISCOUNT_PRODUCT_QUANTITY";

export {
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  SET_FORM_STEP,
  RESET_STATE,
  DISABLE_STEP,
  ADD_PRODUCT_QUANTITY,
  DISCOUNT_PRODUCT_QUANTITY,
};
