const ADD_PRODUCT = "SHOPPING_CAR ADD_PRODUCT";
const REMOVE_PRODUCT = "SHOPPING_CAR REMOVE_PRODUCT";
const SET_FORM_STEP = "SET_FORM_STEP";
const RESET_STATE = "RESET_STATE";

export { ADD_PRODUCT, REMOVE_PRODUCT, SET_FORM_STEP, RESET_STATE };
