const SET_STATUS_REGISTER = "AUTH SET_STATUS_REGISTER";
const SET_STATUS_LOGIN = "AUTH SET_STATUS_LOGIN";
const SET_STATUS_TOKEN = "AUTH SET_STATUS_TOKEN";
const LOGOUT = "AUTH LOGOUT";

export { SET_STATUS_REGISTER, SET_STATUS_LOGIN, SET_STATUS_TOKEN, LOGOUT };
