const SET_PRODUCTS = "PRODUCT SET_PRODUCTS";
const SET_PRODUCT_DETAIL = "PRODUCT SET_PRODUCT_DETAIL";
const SET_PRODUCT_FILTER = "SET_PRODUCT_FILTER";

export { SET_PRODUCTS, SET_PRODUCT_DETAIL, SET_PRODUCT_FILTER };
